### ISSUE TITLE
cheribuild target does not exist

### ISSUE THREAD

**Issue by Bromind** [kent-weak-memory/rust#2]
Hi, 

The Readme indicates to run `./cheribuild.py -d cheribsd-purecap-morello` (https://github.com/kent-weak-memory/rust#build-cheri-bsd), but this returns an error: 
`
Target cheribsd-purecap-morello does not exist. Did you mean cheribsd-release-morello-purecap or cheribsd-riscv64-purecap or cheribsd-morello-purecap?
`

I assume the Readme should be `./cheribuild.py -d cheribsd-morello-purecap` ?

Best,
Martin

**Comment by graymalkin** [comment]
You assume correct. I’ve updated the readme!

Thanks for pointing it out.
